### ISSUE TITLE
FormRuntime.render() causes exception

### ISSUE THREAD

**Issue by kdambekalns** [neos/form#102]
Neos.Form 5.0.0 throws

`Exception in line 340 of /…/Flow_Object_Classes/Neos_Form_Core_Runtime_FormRuntime.php: Argument 1 passed to Neos\Flow\Mvc\ActionResponse::mergeIntoParentResponse() must be an instance of Neos\Flow\Mvc\ActionResponse, instance of Neos\Flow\Mvc\ActionRequest given, called in /…/Flow_Object_Classes/Neos_Form_Core_Runtime_FormRuntime.php on line 340`

Caused by https://github.com/neos/form/blob/28d7bd159be9274bbd86c6eee3818cc68a330b74/Classes/Core/Runtime/FormRuntime.php#L156

**Comment by bwaidelich** [comment]
Doh o.O
