### ISSUE TITLE
Make Flow 7.x compatible

### ISSUE THREAD

**Issue by albe** [neos/form#140]

**Comment by bwaidelich** [comment]
IIRC the form package is compatible with Flow 7 since version 5

**Comment by albe** [comment]
Ah, yes, because it uses the YOLO constraint `>=` :D Then I'd suggest changing that to `^6.0 || ^7.0` to avoid having this installed with a future Flow version that it is not compatible with

**Comment by bwaidelich** [comment]
YOLO constraint, I like ;)

> Then I'd suggest changing that to ^6.0 || ^7.0

Yep, makes sense

**Comment by albe** [comment]
> YOLO constraint, I like ;)

To be fair, the real YOLO constraint is actually `*` - `>=` is it's little brother ;D
