### ISSUE TITLE
Multi-Step forms fail when saving objects in the Form State

### ISSUE THREAD

**Issue by ger4003** [neos/form#143]
In my usecase the FormState holds asset objects like `Neos\Media\Domain\Model\Document` or `Neos\Media\Domain\Model\Image`. When form is rendered with initalized formState having one of the mentioned objects, an exception is thrown:

`
Absorbed Exception: Notice: property_exists(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;Neos\Media\Domain\Model\Document&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in .../Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_Persistence_Doctrine_PersistenceManager.php line 188
`

Is related to #126

**Comment by bwaidelich** [comment]
Thanks again for your report and the PR.
After diving into this I realized that this is actually a very old regression introduced with https://github.com/neos/form/pull/101

So I turned this into a bug ticket and will push a PR with a fix ASAP, that will make the configuration feature obsolete.

Related: #126 #135

**Comment by ger4003** [comment]
Solved by #145
