### ISSUE TITLE
Form values no longer available in custom form elements

### ISSUE THREAD

**Issue by cvette** [neos/form#156]
It used to be possible to get the form values in `AbstractFormElement::onSubmit()`.  But `$formRuntime->getFormState()->getFormValues()` is empty since version **5.3.0**.

## Steps to reproduce

1. Create a [Form with a custom form element](https://gist.github.com/bwaidelich/c2d5afc2759c17cae030104f8bb8fcde) that renders the result of `$formRuntime->getFormState()->getFormValues()` in `onSubmit`
2. Fill out the form and submit

### Expected result

```
array(1)
 'password' (8) => 'aaaa' (4)
```

### Actual result

```
array(empty)
```

## Affected versions

neos/form 5.3.0

**Comment by bwaidelich** [comment]
Do you think that's related to #149 ?

**Comment by bwaidelich** [comment]
...or maybe #155 ?

**Comment by cvette** [comment]
Reverting #149 makes it work again.

**Comment by bwaidelich** [comment]
@cvette could you provide a minimal scenario (or maybe even a breaking test) that demonstrates expected vs actual behavior?

**Comment by bwaidelich** [comment]
@cvette If you lack the time you could maybe provide a short code snippet or at least some context: i.e. were you creating a custom form element? what behavior did you expect, etc.? Cheers :)

**Comment by cvette** [comment]
It's a custom password confirmation form element, i.e. it checks whether the current value matches the value of another field and adds a validation error, if necessary. Yes, there are better ways to do that.

The issue with this change is, that the values are now assigned after all form element onSubmit() methods are invoked. Previously, they were assigned within the same for-loop, therefore you had at least the values for all elements before the current one.

**Comment by dlubitz** [comment]
Any new ideas here? Have also issues now, with conditional required fields based on values of other fields.

**Comment by bwaidelich** [comment]
@dlubitz I'm still looking for ways around this. Could you share some of your code?

**Comment by bwaidelich** [comment]
@cvette @dlubitz I think #160 should solve the issue. Can you confirm?
