### ISSUE TITLE
Support for multiple Fluid template paths in templatePathPattern, partialPathPattern and layoutPathPattern

### ISSUE THREAD

**Issue by sorenmalling** [neos/form#37]
Similar to how you override ex. `TemplateRootPaths` in Views.yaml and allow a array of paths, with support for fallback, the same functionality will be great for 
```
            renderingOptions:
              templatePathPattern: 'resource://{@package}/Private/Form/{@type}.html'
```

when you define preset. 

**Today: ** If you wan't to create a preset with a different `Page` than the `default` preset, you have to copy all files.

**Futury: ** Add a array of paths

I don't know if it's even possible to make complete use of the TemplatePaths object of the Fluid package.

I will personally dig into this in late april (after release of project) in case it's not solved at that time.
So all feedback gathered up untill then will be appreciated.

**Comment by bwaidelich** [comment]
@sorenmalling could you please clarify why you have to "copy all files" - or what you mean with "all" in that case?
To change the rendering of the default page, you only need to change that single template

**Comment by sorenmalling** [comment]
If I was able to add the templatePathPatterns in the `Neos.Form:Base` element, it would automatically look for the different paths instead of changing it for a single element. That is the reason behind this ticket
