### ISSUE TITLE
Discussion: How could it be possible to process submitted data between pages

### ISSUE THREAD

**Issue by sorenmalling** [neos/form#52]
Based on the topic raised here

https://discuss.neos.io/t/neos-form-persist-to-a-entity-between-each-page/2444/4

I would like to know what steps that could be taken, to make it possible to process submitted value in between pages. This is, without having to create a custom page element, but simple use the shipped Neos.Form:Page

Some of the thought I've had:

**What if the user go back/forth in the form a.k.a. re-processing**

This should not be the task of this patch to take care of that

**How can we add any created data / outcome of processing to the form**

**Why us onSubmit not called for Page form element** 
Could this be a low-hanging fruit that we can pick simply by letting **onSubmit** be called also on Page element?

**Comment by bwaidelich** [comment]
@sorenmalling Any particular reason why you want to move the discussion here? IMO discuss.neos.io is the best place for it
