### ISSUE TITLE
Quickstart Example not complete

### ISSUE THREAD

**Issue by christophlehmann** [neos/form#7]
typo3/flow: ^3.1
typo3/form: ^2.0

I followed the steps
- Create your first form
- Render a form

In the frontend i get `Catchable Fatal Error: Argument 1 passed to My\Package\Forms\TestForm_Original::build() must be of the type array, null given` so there must be something more to do

Also the links in `http://flow-form-framework.readthedocs.org/en/latest/quickstart.html` are broken

**Comment by bwaidelich** [comment]
Sorry for the long delay on this one..
#62 fixes the ViewHelper in question for the upcoming version.
For older versions this can be worked around by specifying the `overridenConfiguration` argument such as
```html
<form:render factoryClass="Your\Package\QuickstartFactory" overrideConfiguration="{foo: 'bar'}" />
```
