### ISSUE TITLE
Handle empty default values in `AbstractFinisher` correctly

### ISSUE THREAD

**Issue by futape** [neos/form#75]
currently the parseOption function behaves as follows:
1. if the option is set (i.e. it exists and is not an empty string), resolve the object accessors (if a string) and returns the it
2. otherwise, return the default option, if one exist, with resolved object accessors (if a string), or `null` if it doesn't

this means, assuming there is no default option, that an initial value of an empty string returns null.
however, a value containing an object accessor (e.g. `{foo}`) will never return null - even if the result is empty.

from my perspective there are two issues:
+ the same rules that apply to the option should apply to the default option (i.e. return null if empty).
+ after resolving the object accessors, null should be returned if the resulting string is an empty one (currently an empty string would be returned) - again, this should apply to both, options and default options

**Comment by bwaidelich** [comment]
Sorry for the delay.. #69 should fix this
