### ISSUE TITLE
EMailfinisher - RecipientName check when RecipientAddress is in Array causes errors

### ISSUE THREAD

**Issue by svwu** [neos/form#77]
Hello,
since the Recipientaddress may be an array of addresses the finisher checks, if the recipientName is an empty string with type check.
`
        if (is_array($recipientAddress) && $recipientName !== '') {
            throw new FinisherException('The option "recipientName" cannot be used with multiple recipients in the EmailFinisher.', 1483365977);
        }`

Since the E-Mailfinisher can be used with configured values from a yaml file, the recipientName will be transmitted as null when it is not set. 

`null !== ''`
will return true and cause in a false validated recipientName so it's not possible to set recipientAddresses as an array.

**Comment by kitsunet** [comment]
so !empty($recipientName) would be more helpful I guess.
