### ISSUE TITLE
RedirectFinisher does redirect after rendering

### ISSUE THREAD

**Issue by DrillSergeant** [neos/form#84]
**Scenario:**
I use the Form-Framework via FormBuilder inside a Neos project. We have node based form with 2 finishers:
* EMail-Finisher (sends a mail to an admin-mailbox)
* Redirect-Finisher (redirects to a thankyou-document-node)

**Expected behaviour:**
After submitting the form (when validation does not complain), the users gets redirected to the thankyou-document-uri.

**Actual behavirour:**
The redirect is working, but before it happens, the document of the form is rendered and visible for 1-2s and then the redirct happens.

Can we achive that the redirect happens without the "intermediate rendering" of the form?

**Comment by bwaidelich** [comment]
I knew I had seen this before somewhere: https://github.com/neos/neos-development-collection/pull/16
