### ISSUE TITLE
MaxLength is not registered in TextAreaViewhelper

### ISSUE THREAD

**Issue by zabusm** [neos/form#87]
https://github.com/neos/form/blob/5df8e93ddc2678ed2b3aff2761cbac0e134e956f/Resources/Private/Form/MultiLineText.html#L4

In Neos 4.1.7 I am getting the error that maxlength is no declared argument in TextAreaViewHelper.

**Comment by kitsunet** [comment]
Yep, seems to me that is just wrong. TextFieldVH does support it, but TextArea does not atm. (Although the textarea element supports it. So we might want to add it).

**Comment by robertlemke** [comment]
@zabusm for the time being you can work around this bug by installing _neos/form_ 4.1.5
@bwaidelich I'll take a look

**Comment by bwaidelich** [comment]
@zabusm could you quickly verify that #88 solves the issue for you then I could quickly trigger a new release.

**Comment by zabusm** [comment]
@bwaidelich yes, it works.

**Comment by bwaidelich** [comment]
@zabusm Thanks, `neos/form` 4.2.1 contains the fix
