### ISSUE TITLE
RedirectFinisher causes double slash

### ISSUE THREAD

**Issue by DrillSergeant** [neos/form#89]
*Steps to reproduce:*

* Create a form with a redirectFinisher pointing to a document node (I used the form builder package and created a node based form)
* Publish the form
* Fill out the form in the frontend and submit it

*Expected behavior*
You get redirected to the destination node and the uri is fine.

*Actual behaviour*
The uri contains a double-slash.

I think the reason is found here: https://github.com/neos/form/blame/3d4bccd33df9f2e4099312543d65b6198633c6c3/Classes/Finishers/RedirectFinisher.php#L58
$request->getHttpRequest()->getBaseUri() has a trailing slash and $uri has a leading slash.

As a workaround I changed the form-builder fusion to generate an absolute uri for the redirect:
```
prototype(Neos.Form.Builder:NodeBasedFinisherCollection) {
    itemRenderer {
        redirectFinisher {
            renderer {
                element.options {
                    uri.@process.convertNodeUris.absolute = ${true}
                }
            }
        }
    }
}
```
But I think the code, that prepends scheme and host to the uri should be fixed in the form package.

**Comment by simstern** [comment]
https://github.com/neos/form/pull/96 will fix this.
